version: 2
jobs:
  build:
    docker:
      - image: jackfirth/racket
    steps:
      - checkout
      - run:
          name: Install
          command: raco pkg install --auto --link --name rebellion
      - run:
          name: Test
          command: raco test -p --drdr rebellion
