name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: jackfirth/racket-package-ci-action@master
      with:
        name: rebellion
